# Generated by Django 6.0 on 2026-02-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(help_text="Tell us why you're the perfect fit", verbose_name='Cover Letter')),
                ('resume', models.FileField(blank=True, null=True, upload_to='application_resumes/', verbose_name='Resume')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
