# Generated by Django 6.0 on 2026-02-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job Title', max_length=200)),
                ('description', models.TextField(verbose_name='Job Description')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('salary_range', models.CharField(help_text='e.g. $80,000 - $120,000 / Year', max_length=100, verbose_name='Salary Range')),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], default='full_time', max_length=20, verbose_name='Employment Type')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='Posted Date')),
            ],
        ),
    ]
